kotlin.code.style=official
org.gradle.configuration-cache=false
org.gradle.caching=true
org.gradle.parallel=true
org.gradle.jvmargs=-Xmx1g -XX:MaxMetaspaceSize=768m
paralyabot.version=99.99.99
paralyabot.class-path=""
plugin.lg.version=99.99.99
plugin.sta.version=99.99.99
plugin.ai.version=99.99.99
module.deps.version=99.99.99
module.common.version=99.99.99
module.common.min-compatible-version=1.0.0